#10 rounds of Roshambo by Coppery

win="You won!!!"
loss="You lost... *sad trombone*"
draw="You tied with me"
print("Hello, welcome to Roshambo (Rock, Paper, Scissors) by Coppery")
print("There will be 10 rounds, have fun! ^-^")
input("Press [ENTER] to start game")

print("Round 1")
choice1=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice1)
print("I chose paper")
print("If you chose Rock: " + loss)
print("If you chose Paper: " + draw)
print("If you chose Scissors: " + win)
input("Press [ENTER] to continue")

print("Round 2")
choice2=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice2)
print("I chose Scissors")
print("If you chose Rock: " + win)
print("If you chose Paper: " + loss)
print("If you chose Scissors: " + draw)
input("Press [ENTER] to continue")

print("Round 3")
choice3=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice3)
print("I chose Rock")
print("If you chose Rock: " + draw)
print("If you chose Paper: " + win)
print("If you chose Scissors: " + loss)
input("Press [ENTER] to continue")

print("Round 4")
choice4=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice4)
print("I chose Rock")
print("If you chose Rock: " + draw)
print("If you chose Paper: " + win)
print("If you chose Scissors: " + loss)
input("Press [ENTER] to continue")

print("Round 5")
choice5=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice5)
print("I chose Scissors")
print("If you chose Rock: " + win)
print("If you chose Paper: " + loss)
print("If you chose Scissors: " + draw)
input("Press [ENTER] to continue")

print("Round 6")
choice6=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice6)
print("I chose Paper")
print("If you chose Rock: " + loss)
print("If you chose Paper: " + draw)
print("If you chose Scissors: " + win)
input("Press [ENTER] to continue")

print("Round 7")
choice7=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice7)
print("I chose Paper")
print("If you chose Rock: " + loss)
print("If you chose Paper: " + draw)
print("If you chose Scissors: " + win)
input("Press [ENTER] to continue")

print("Round 8")
choice8=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice8)
print("I chose Rock")
print("If you chose Rock: " + draw)
print("If you chose Paper: " + win)
print("If you chose Scissors: " + loss)
input("Press [ENTER] to continue")

print("Round 9")
choice9=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice9)
print("I chose Paper")
print("If you chose Rock: " + loss)
print("If you chose Paper: " + draw)
print("If you chose Scissors: " + win)
input("Press [ENTER] to continue")

print("Round 10")
choice10=input("Enter Rock, Paper or Scissors: ")
print("You chose: " + choice10)
print("I chose Rock")
print("If you chose Rock: " + draw)
print("If you chose Paper: " + win)
print("If you chose Scissors: " + loss)
input("Press [ENTER] to end game")

print("Thanks for playing Roshmabo! ^-^")
print("I should learn if/else so i can make point system :P")
print(">͎Y͎o͎u͎'͎r͎e͎ ͎v͎e͎r͎y͎ ͎p͎r͎e͎t͎t͎y͎ ͎:͎3͎<͎")
